---
apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app: krakend
  ports:
    - name: http
      protocol: TCP
      port: 8080
    - name: stats
      protocol: TCP
      port: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: hands-on-krakend
        ports:
        - containerPort: 8080
        - containerPort: 8090
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "500m"
            memory: "128Mi"